### ISSUE TITLE
temp not found

### ISSUE THREAD

**Issue by aabeben** [only52607/smali2java#1]
I've tried to convert small file into java file but no luck. below is screenshot. Would you like to help me about the issue, I mean the author
![Screen Shot 2021-11-12 at 09 33 55](https://user-images.githubusercontent.com/3040183/141399246-a7c0ff3b-00df-4bf4-b254-8deffb67342c.png)
.

**Comment by only52607** [comment]
You can try manually creating the directory “/Support/Code...../temp” above and try again.

**Comment by CyrilHu** [comment]
I have this issue on macOS, the VSCode user directory is /Users/user/Library/Application Supports/Code/User....../temp.
the directory path has a blank character. so your command line should user double quotes "" to wrap your path. otherwise, the path will lost the beginning part before the blank character.

**Comment by CyrilHu** [comment]
@only52607 I had make a pull request to fix this issue, please review and merge.
